from enum import Enum
import re
from typing import List
import torch
import string
import statistics
import pickle
from medspacy.sentence_splitting import PyRuSHSentencizer
import medspacy
from medspacy.preprocess import PreprocessingRule, Preprocessor
from medspacy.ner import TargetRule
from medspacy.context import ConTextRule
from medspacy.section_detection import Sectionizer
from medspacy.postprocess import PostprocessingRule, PostprocessingPattern, Postprocessor
from medspacy.postprocess import postprocessing_functions
from medspacy.visualization import visualize_ent, visualize_dep
from medspacy.ner import TargetRule
from medspacy.visualization import visualize_ent
from medspacy.section_detection import SectionRule
import spacy
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import urllib.request
import dill as pickle
from string import digits
import json


#medspacy text pipeline
warnings.filterwarnings('ignore')
#nlp = spacy.load("en_ner_bc5cdr_md", disable={"tok2vec","tagger", "attribute_ruler", "lemmatizer", "parser"})
nlp = medspacy.load()
nlp.remove_pipe("medspacy_context")
preprocessor = Preprocessor(nlp.tokenizer)
nlp.tokenizer = preprocessor
preprocess_rules = [
   # PreprocessingRule(lambda x: x.lower(), desc="Lowercase text"),
    PreprocessingRule(r"~", repl=" ", desc="crush tilda"),
    PreprocessingRule(r"\[\*\*[^\]]+\]", desc="Remove all other bracketed placeholder text from MIMIC"),
    PreprocessingRule("dx'd", repl="Diagnosed", desc="Replace abbreviation"),
    PreprocessingRule(r"tx'd", repl="Treated", desc="Replace abbreviation"),
    PreprocessingRule(r"\[\*\*[\d]{1,4}-[\d]{1,2}(-[\d]{1,2})?\*\*\]", repl="01-01-2010", desc="Replace MIMIC date brackets with a generic date."),
    PreprocessingRule(r"\[\*\*[\d]{4}\*\*\]", repl="2010", desc="Replace MIMIC year brackets with a generic year."),
]

preprocessor.add(preprocess_rules)
target_matcher = nlp.get_pipe("medspacy_target_matcher")

target_rules = [
    TargetRule("hemicolectomy", "treatment"),
    TargetRule("hydrochlorothiazide", "treatment"),
    TargetRule("colon cancer", "disease"),
    TargetRule("radiotherapy", "disease",
              pattern=[{"lower": "xrt"}]),
    TargetRule("metastasis", "disease"),
    TargetRule("acs", "disease",
              pattern=[{"lower": {"in": ["mi", "nstemi", "stemi"]}}]),
    TargetRule("heart attack", "disease"),
    TargetRule("myocardial infarction", "disease"),
    TargetRule("abdominal aortic aneurysm", "disease"),
    TargetRule("aaa", "disease"),
    TargetRule("triple a", "disease"),
    TargetRule("aortic aneurysm", "disease"),
    TargetRule("abd aorta enlarged", "disease"),
    TargetRule("enlarged aorta", "disease"),
    TargetRule("tachycardia", "disease"),
    TargetRule("svt", "disease"),
    TargetRule("afib with rvr", "disease"),
    TargetRule("afib", "disease"),
    TargetRule("vtach", "disease"),
    TargetRule("ventricular tachycardia", "disease",
              pattern=[{"lower": {"in": ["atrial", "supraventricular", "a", "v", "sinus", "multifocal atrial", "ventricular"]}},
                       {"lower": {"in": ["tachycardia", "tach", "fibrillation", "fib", "flitter", "flutter"]}}]),
    TargetRule("atrial flutter", "disease",
              pattern=[{"lower": {"in": ["atrial", "ventricular"]}},
                       {"lower": {"in": ["tachycardia", "tach"]}}]),
    TargetRule("heart block", "disease"),
    TargetRule("wenckebach", "disease"),
    TargetRule("congestive heart failure", "disease"),
    TargetRule("heart failure", "disease"),
    TargetRule("cardiac failure", "disease"),
    TargetRule("low ejection fraction", "disease"),
    TargetRule("low ef", "disease"),
    TargetRule("congestive heart", "disease"),
    TargetRule("bradycardia", "disease"),
    TargetRule("malignant hypertension", "disease"),
    TargetRule("tachycardia", "disease",
               pattern=[{"lower": {"in": ["tachycardia", "tachycardic"]}}]),
    TargetRule("chf", "disease",
               pattern=[{"lower": {"in": ["chf", "hfref", "hfpef", "cardiomyopathy"]}}]),
    TargetRule("htn emergency", "disease",
               pattern=[{"lower": {"in":   ["htn", "hypertensive", "hypertension"]}},
                        {"lower": {"in":   ["crisis", "urgency", "emergency"]}}]),
    TargetRule("hypotension", "disease",
               pattern=[{"lower": {"in": ["hypotension", "hypotensive", "shock", "malperfusion", "hypoperfuse", "hypoperfusion"]}}]),
    TargetRule("pressors", "treatment",
               pattern=[{"lower": {"in":   ["pressors", "levophed", "pressor", "levo", "norepi", "norepinephrine", "neosynephrine", "vasopressin"]}}]),
    TargetRule("cardiac arrest", "disease",
               pattern=[{"lower": {"in": ["cardiopulmonary", "cardiac"]}},
                        {"lower": {"in": ["arrest", "death"]}}]),
    TargetRule("cardiopulmonary resuscitation", "treatment",
               pattern=[{"lower": {"in": ["cardiopulmonary",  "cardiac", "cardio"]}},
                        {"lower": {"in": ["resuscitation", "defib", "defibrillate", "defibrillation"]}}]),
    TargetRule("cpr", "treatment"),
    TargetRule("chronic obstructive lung disease", "treatment"),
    TargetRule("chronic obstructive pulmonary disease", "treatment"),
    TargetRule("tuberculosis", "treatment"),
    TargetRule("ntm", "treatment"),
    TargetRule("tb", "treatment"),
    TargetRule("tbm", "treatment"),
    TargetRule("airway obstruction", "disease",
               pattern=[{"lower": {"in": ["tracheal", "airway"]}},
                        {"lower": {"in": ["stenosis", "obstruction", "edema", "mass"]}}]),
    TargetRule("vocal chord edema", "disease",
               pattern=[{"lower": {"in": ["vocal", "airway"]}},
                        {"lower": {"in": ["chord"]}},
                        {"lower": {"in": ["swelling", "edema", "dysfunction"]}}]),
    TargetRule("copd", "disease",
               pattern=[{"lower": {"in": ["copd"]}}]),
    TargetRule("pneumonia", "disease",
               pattern=[{"lower": {"in":  ["pna", "pneumonia", "cap", "hcap", "vap"]}}]),
    TargetRule("pneumonia", "disease",
               pattern=[{"lower": {"in": ["lung", "pulmonary", "multifocal"]}},
                        {"lower": {"in": ["infection", "infiltrate", "consolidation"]}}]),
    TargetRule("perfusion defect", "disease"),
    TargetRule("ptx", "disease",
               pattern=[{"lower": {"in": ["collapsed", "lung", "pulmonary"]}},
                        {"lower": {"in": ["lung", "collapsed", "collapse"]}}]),
    TargetRule("air around lung", "disease"),
    TargetRule("ptx", "disease",
               pattern=[{"lower": {"in":  ["ptx", "pneumothorax", "pneumothoraces"]}}]),
    TargetRule("respiratory failure", "disease",
               pattern=[{"lower": {"in": ["respiratory", "resp", "resp", "pulmonary"]}},
                        {"lower": {"in": ["arrest", "failure", "arrest", "distress"]}}]),
    TargetRule("intubated", "treatment",
               pattern=[{"lower": {"in":  ["intubated", "vented", "ventilator", "ventilated"]}}]),
    TargetRule("liver failure", "disease",
               pattern=[{"lower": {"in": ["liver", "hepatic"]}},
                        {"lower": {"in": ["cirrhosis", "ascites", "cirrhosis", "cirrhotic", "varices"]}}]),
    TargetRule("left upper quadrant pain", "treatment"),
    TargetRule("right upper quadrant pain", "treatment"),
    TargetRule("right lower quadrant pain", "treatment"),
    TargetRule("hepatitis", "treatment"),
    TargetRule("transaminitis", "treatment"),
    TargetRule("abdominal pain", "disease",
               pattern=[{"lower": {"in": ["abdominal", "stomach", "gastric", "ruq", "luq", "rlq", "llq", "chest", "shoulder", "back", "neck", "ear"]}},
                        {"lower": {"in": ["pain", "discomfort", "distress", "dolor", "upset"]}}]),
    TargetRule("gi bleed", "disease",
               pattern=[{"lower": {"in":  ["gastrointestinal", "gi", "variceal", "gastric", "gastro", "intestinal", "stomach"]}},
                        {"lower": {"in":  ["bleed", "bleeding", "hemorrhage", "ooze"]}}]),
    TargetRule("gib", "disease"),
    TargetRule("hematchezia", "disease"),
    TargetRule("melena", "disease"),
    TargetRule("vomiting blood", "disease"),
    TargetRule("blood per rectum", "disease"),
    TargetRule("brbpr", "disease"),
    TargetRule("GIB", "disease",
               pattern=[{"lower": {"in":  ["blood per rectum"]}}]),
    TargetRule("inflamed pancreas", "disease"),
    TargetRule("elevated lipase", "disease"),
    TargetRule("pancreatic inflammation", "disease"),
    TargetRule("pancreatitis", "disease",
               pattern=[{"lower": {"in":  ["pancreatitis"]}}]),
    TargetRule("colitis", "disease",
               pattern=[{"lower": {"in":  ["colitis", "cdiff"]}}]),
    TargetRule("colitis", "disease",
               pattern=[{"lower": {"in":  ["c", "clostridium", "clostridia", "clostridial", "cdiff", "cdifficile"]}},
                        {"lower": {"in":  ["colitis", "diff", "difficile"]}}]),
    TargetRule("bowel infection", "disease"),
    TargetRule("gut inflammation", "disease"),
    TargetRule("bowel inflammation", "disease"),
    TargetRule("inflamed bowel", "disease"),
    TargetRule("blood infection", "disease"),
    TargetRule("positive blood culture", "disease"),
    TargetRule("gram negatives in blood", "disease"),
    TargetRule("+ blood culture", "disease"),
    TargetRule("gastroenteritis", "disease",
               pattern=[{"lower": {"in":  ["gastroenteritis", "enteritis"]}}]),
    TargetRule("bacteremia", "disease",
               pattern=[{"lower": {"in":  ["bacteremia", "septicemia"]}}]),
    TargetRule("meningitis", "disease",
               pattern=[{"lower": {"in":  ["meningitis"]}}]),
    TargetRule("endocarditis", "disease",
               pattern=[{"lower": {"in":  ["endocarditis", "vegetation"]}}]),
    TargetRule("nuchal rigidity ", "disease"),
    TargetRule("cns infection", "disease"),
    TargetRule("encephalitis", "disease"),
    TargetRule("septic emboli", "disease"),
    TargetRule("urinary tract infection", "disease"),
    TargetRule("positive urine", "disease"),
    TargetRule("irregularly irregular", "disease"),
    TargetRule("uti", "disease",
               pattern=[{"lower": {"in": ["uti", "dysuria"]}}]),
    TargetRule("diabetes mellitus", "disease"),
    TargetRule("dmt2", "disease"),
    TargetRule("iddm", "disease"),
    TargetRule("iddm2", "disease"),
    TargetRule("dm2", "disease"),
    TargetRule("dm", "disease",
              pattern=[{"lower": {"in": ["dm", "diabetes"]}}]),
    TargetRule("diabetic ketoacidosis", "disease",
               pattern=[{"lower": {"in":  ["diabetic", "diabetes"]}},
                        {"lower": {"in":  ["ketoacidosis", "ketoacidotic", "ketosis"]}}]),
    TargetRule("dka", "disease",
              pattern=[{"lower": {"in": ["dka", "ketoacidosis", "ketosis"]}}]),
    TargetRule("ich", "disease",
               pattern=[{"lower": {"in": ["intracranial", "intraventricular", "intracerebral", "brain", "cerebral"]}},
                        {"lower": {"in": ["hemorrhage", "hemorrhaging", "bleed", "hematoma"]}}]),
    TargetRule("sdh", "disease",
               pattern=[{"lower": {"in": ["subdural", "dural"]}},
                        {"lower": {"in": ["hemorrhage", "hemorrhaging", "bleed", "hematoma"]}}]),
    TargetRule("sah", "disease",
               pattern=[{"lower": {"in": ["subarachnoid", "arachnoid"]}},
                        {"lower": {"in": ["hemorrhage", "hemorrhaging", "bleed", "hematoma"]}}]),
    TargetRule("ich", "disease",
               pattern=[{"lower": {"in": ["ivh", "ich"]}}]),
    TargetRule("sdh", "disease",
               pattern=[{"lower": {"in": ["sdh"]}}]),
    TargetRule("sah", "disease",
               pattern=[{"lower": {"in": ["sah"]}}]),
    TargetRule("seizure", "disease",
               pattern=[{"lower": {"in":   ["seizure", "seizures", "epilepsy", "convulsion", "pseudoseizure"]}}]),
    TargetRule("pulmonary embolism", "disease",
               pattern=[{"lower": {"in": ["pulmonary", "saddle", "lung"]}},
                        {"lower": {"in": ["embolus", "clot", "embolisms", "embolism", "emboli"]}}]),
    TargetRule("ckd", "disease",
               pattern=[{"lower": {"in":  ["ckd", "ckd1", "ckd2", "ckd3", "ckd4", "ckd5"]}}]),
    TargetRule("end-stage renal disease", "disease"),
    TargetRule("end stage kidney disease", "disease"),
    TargetRule("esrd", "disease"),
    TargetRule("chronic kidney disease", "disease",
               pattern=[{"lower": {"in": ["chronic", "acute", "endstage"]}},
                        {"lower": {"in": ["kidney", "renal", "nephrogenic"]}},
                        {"lower": {"in": ["disease", "failure", "injury", "dysfunction", "disease"]}}]),
    TargetRule("pe", "disease",
               pattern=[{"lower": {"in": ["pe"]}}]),
    TargetRule("alcohol withdrawal", "disease",
               pattern=[{"lower": {"in": ["alcohol", "etoh", "alcoholic", "delirium"]}},
                        {"lower": {"in": ["withdrawal", "tremens", "hallucinosis", "hallucination"]}}]),
    TargetRule("hypertension", "disease",
               pattern=[{"lower": {"in": ["htn", "hypertension", "hypertensive"]}}]),
    TargetRule("asthma", "disease",
               pattern=[{"lower": {"in": ["asthma", "asthmatic"]}}]),
    TargetRule("coronary artery disease", "disease",
               pattern=[{"lower": {"in":  ["coronary", "heart"]}},
                        {"lower": {"in":  ["artery", "vessel"]}},
                        {"lower": {"in":  ["disease", "occlusion", "obstruction", "spasm"]}}]),
    TargetRule("cad", "disease",
               pattern=[{"lower": {"in":  ["cad"]}}]),
    TargetRule("high blood pressure", "disease"),
    TargetRule("elevated blood pressure", "disease"),
    TargetRule("coronary obstruction", "disease"),
    TargetRule("hypothyroidism", "disease",
               pattern=[{"lower": {"in":  ["hypothyroidism", "hypothyroid", "myxedema"]}}]),
    TargetRule("hypoactive thyroid", "disease"),
    TargetRule("myxedema coma", "disease"),
    TargetRule("hyperactive thyroid", "disease"),
    TargetRule("hyperthyroidism", "disease",
               pattern=[{"lower": {"in":  ["hyperthyroidism","hyperthyroid",  "graves"]}}]),
    TargetRule("cva", "disease",
               pattern=[{"lower": {"in":  ["cva", "stroke"]}}]),
    TargetRule("ischemic stroke", "disease",
               pattern=[{"lower": {"in":  ["ischemic", "ischaemic", "mca", "pca", "aca", "hemorrhagic", "cerebrovascular"]}},
                        {"lower": {"in":  ["stroke", "accident"]}}]),
    TargetRule("osa", "disease",
               pattern=[{"lower": {"in":  ["osa"]}}]),
    TargetRule("obstructive sleep apnea", "disease"),
    TargetRule("sleep apnea", "disease"),
    TargetRule("high cholesterol", "disease"),
    TargetRule("delirium", "disease",
               pattern=[{"lower": {"in":  ["delirium", "confusion", "sundowning", "sundown", "sundowning", "confused", "delirious", "encephalopathy", "encephalopathic"]}}]),
    TargetRule("delirium", "disease",
               pattern=[{"lower": {"in":  ["altered", "poor" "alteration"]}},
                        {"lower": {"in":  ["mental", "confusional"]}},
                        {"lower": {"in":  ["status", "state"]}}]),
    TargetRule("hyperlipidemia", "disease",
               pattern=[{"lower": {"in":  ["hyperlipidemia", "hld", "hld", "dld", "dld", "dyslipidemia", "dyslipidemic", "hyperlipidemic", "hypertriglyceridemia"]}}]),
    TargetRule("adrenal insufficiency", "disease"),
    TargetRule("low cortisol", "disease"),
    TargetRule("cushings disease", "disease"),
    TargetRule("hypocortisolemia", "disease",
               pattern=[{"lower": {"in":  ["hypoaldosteronism", "hypoaldosterone", "ai"]}}]),
    TargetRule("cushings", "disease",
               pattern=[{"lower": {"in":  ["cushings", "hypercortisolemia", "hyperaldosteronism", "hyperaldosterone", "cushingoid", "cushing"]}}]),
    TargetRule("lupus", "disease",
               pattern=[{"lower": {"in":  ["lupus", "sle"]}}]),
    TargetRule("systemic lupus erythematosus", "disease"),
    TargetRule("lupus erythematosus", "disease"),
    TargetRule("systemic lupus", "disease"),
    TargetRule("high cortisol", "disease"),
    TargetRule("residual deficits", "disease"),
    TargetRule("systemic sclerosis", "disease"),
    TargetRule("hemopericardium", "disease"),
    TargetRule("pneumopericardium", "disease"),
    TargetRule("pneumoperitoneum", "disease"),
    TargetRule("hemoperitoneum", "disease"),
    TargetRule("scleroderma", "disease",
               pattern=[{"lower": {"in":  ["scleroderma", "crest", "crest", "sclerodactyly"]}}]),
    TargetRule("pericardial effusion", "disease",
               pattern=[{"lower": {"in":  ["pericardial", "epicardial", "becks"]}},
                        {"lower": {"in":  ["effusion", "tamponade",  "triad", "fluid", "hemopericardium"]}}]),
    TargetRule("cholecystitis", "disease"),
    TargetRule("cholecystitis", "disease",
               pattern=[{"lower": {"in": ["gallbladder", "inflamed", "necrotic", "hemorrhagic"]}},
                        {"lower": {"in": ["infection", "inflammation", "edema", "gallbladder", "necrosis"]}}]),
    TargetRule("ards", "disease",
               pattern=[{"lower": {"in":  ["ards"]}}]),
    TargetRule("acute respiratory distress syndrome", "disease"),
    TargetRule("respiratory distress syndrome", "disease"),
    TargetRule("cellulitis", "disease"),
    TargetRule("skin infection", "disease",
               pattern=[{"lower": {"in":  ["skin", "nec", "necrotizing", "cellulitis", "cellulitic"]}},
                        {"lower": {"in":  ["infection", "fasc", "fasciitis", "inflammation"]}}]),
    TargetRule("traumatic brain injury", "disease"),
    TargetRule("brain injury", "disease",
               pattern=[{"lower": {"in":  ["brain", "coup", "head"]}},
                        {"lower": {"in":  ["tbi", "tbi", "trauma", "contracoup", "injury"]}}]),
    TargetRule("tbi", "disease",
               pattern=[{"lower": {"in":  ["tbi"]}}]),
    TargetRule("cancer", "disease",
               pattern=[{"lower": {"in":  ["cancer", "ca"]}}]),
    TargetRule("burn", "disease",
               pattern=[{"lower": {"in":  ["burn"]}}]),
    TargetRule("thermal injury", "disease"),
    TargetRule("cp", "disease"),
    TargetRule("pvd", "disease"),
    TargetRule("pad", "disease"),
    TargetRule("gbm", "disease"),
    TargetRule("glioblastoma", "disease"),
    TargetRule("astrocytoma", "disease"),
    TargetRule("schwanomma", "disease"),
    TargetRule("peripheral vascular disease", "disease",
               pattern=[{"lower": {"in":  ["peripheral", "distal"]}},
                        {"lower": {"in":  ["vascular", "artery", "arterial", "venous", "vein"]}},
                        {"lower": {"in":  ["disease", "dysfunction"]}}]),
    TargetRule("brain tumor", "disease",
               pattern=[{"lower": {"in":  ["brain", "glioblastoma", "cerebral", "supratentorial"]}},
                        {"lower": {"in":  ["met", "metastasis", "tumor", "abscess", "cyst" "multiforme", "mass"]}}]),
    TargetRule("gerd", "disease",
               pattern=[{"lower": {"in":  ["gerd"]}}]),
    TargetRule("gastroesophageal reflux disease", "disease",
               pattern=[{"lower": {"in":  ["gastroesophageal reflux disease"]}}]),
    TargetRule("gastroesophageal refluxes", "disease"),
    TargetRule("gastric reflux", "disease"),
    TargetRule("empyema", "disease"),
    TargetRule("reflux disease", "disease"),
    TargetRule("hemothorax", "disease"),
    TargetRule("pleural effusion", "disease",
               pattern=[{"lower": {"in":  ["pleural", "lung", "complicated ", "loculated"]}},
                        {"lower": {"in": ["fluid", "effusion"]}}]),
    TargetRule("vancomycin", "treatment",
               pattern=[{"lower":  {"in": ["vancomycin", "vanco", "vancocin"]}}]),
    TargetRule("ceftriaxone", "treatment",
               pattern=[{"lower": {"in": ["rocephin", "ceftriaxone"]}}]),
    TargetRule("cefepime", "treatment",
               pattern=[{"lower": {"in": ["maxipime", "cefepime"]}}]),
    TargetRule("piperacillin", "treatment",
               pattern=[{"lower": {"in": ["zosyn", "piperacillin/tazobactam", "pip", "pip/tazo", "pip-tazo", "piptazo"]}}]),
    TargetRule("tazobactam", "treatment",
               pattern=[{"lower": {"in": ["zosyn", "piperacillin/tazobactam", "tazo", "pip/tazo", "pip-tazo", "piptazo"]}}]),
    TargetRule("tigacycline", "treatment",
               pattern=[{"lower": {"in": ["tygacil", "tigacycline"]}}]),
    TargetRule("amikacin", "treatment",
               pattern=[{"lower": {"in": ["amikacin"]}}]),
    TargetRule("meropenem", "treatment",
               pattern=[{"lower": {"in": ["meropenem"]}}]),
    TargetRule("imipenem", "treatment",
               pattern=[{"lower": {"in": ["imipenem"]}}]),
    TargetRule("ertapenem", "treatment",
               pattern=[{"lower": {"in": ["ertapenem"]}}]),
    TargetRule("ampicillin", "treatment",
               pattern=[{"lower": {"in":  ["unasyn", "ampicillin/sulbactam", "amp/sulbactam", "amp", "amp-sulbactam"]}}]),
    TargetRule("sulbactam", "treatment",
               pattern=[{"lower": {"in":  ["unasyn", "ampicillin/sulbactam", "amp/sulbactam", "amp", "amp-sulbactam"]}}]),
    TargetRule("gentamicin", "treatment",
               pattern=[{"lower": {"in": ["gentamicin"]}}]),
    TargetRule("cabg", "treatment"),
    TargetRule("cab", "treatment"),
    TargetRule("cabg x1", "treatment",
               pattern=[{"lower": {"in": ["cabg", "cab"]}},
                        {"lower": {"in": ["x1", "x2", "x3", "x4"]}}]),
    TargetRule("coronary artery bypass graft", "treatment"),
    TargetRule("coronary artery bypass grafting", "treatment"),
    TargetRule("gout", "disease"),
    TargetRule("schwannoma", "disease"),
    TargetRule("cheng", category='cheng', pattern=[{'LOWER': {'IN': ['cheng', 'cheng-hsi']}}]),
    TargetRule("suarez", category='suarez', pattern=[{'LOWER': {'IN': ['suarez']}}]),
    TargetRule("sweeney", category='sweeney', pattern=[{'LOWER': {'IN': ['sweeney', 'sweeny']}}]),
    TargetRule("george", category='george', pattern=[{'LOWER': {'IN': ['george', 'joggy']}}]),
    TargetRule("goel", category='goel', pattern=[{'LOWER': {'IN': ['goel']}}]),
    TargetRule("wolf", category='wolf', pattern=[{'LOWER': {'IN': ['wolf']}}]),
    TargetRule("guha", category='guha', pattern=[{'LOWER': {'IN': ['guha']}}]),
    TargetRule("reul", category='reul', pattern=[{'LOWER': {'IN': ['reul']}}]),
    TargetRule("kleiman", category='kleiman', pattern=[{'LOWER': {'IN': ['kleiman']}}]),
    TargetRule("ramchandani", category='ramchandani', pattern=[{'LOWER': {'IN': ['ramchandani']}}]),
    TargetRule("lawrie", category='lawrie', pattern=[{'LOWER': {'IN': ['lawrie']}}]),
    TargetRule("reardon", category='reardon', pattern=[{'LOWER': {'IN': ['reardon']}}]),
    TargetRule("steele", category='steele', pattern=[{'LOWER': {'IN': ['steele']}}]),
    TargetRule("trask", category='trask', pattern=[{'LOWER': {'IN': ['trask']}}]),
    TargetRule("taylor", category='taylor', pattern=[{'LOWER': {'IN': ['taylor']}}]),
    TargetRule("extremity balloon angioplasty", 'EXTREMITY_ANGIOGRAM'),
    TargetRule("EXTREMITY_ANGIOGRAM", "EXTREMITY_ANGIOGRAM",
              pattern=[{'LOWER': {'IN': ['extremity', 'rue', 'rle', 'lle', 'lue']}},
                       {'LOWER': {'IN': ['angiogram', 'angio']}}]),
    TargetRule("TRANSPLANTATION_LUNG", category='lung_transplant',
              pattern=[{'LOWER': {'IN': ['transplantation', 'lung']}},
                       {'LOWER': {'IN': ['lung', 'transplantation', 'transplant']}}]),
    TargetRule("PERICARDIAL_WINDOW", category='pericardial_window',
              pattern=[{'LOWER': {'IN': ['pericardial']}},
                       {'LOWER': {'IN': ['window']}}]),
    TargetRule("CORONARY_ANGIOGRAM", category='CORONARY_ANGIOGRAM', pattern=[{'LOWER': {'IN': ['rhc', 'lhc']}}]),
    TargetRule("CORONARY_ANGIOGRAM", category='CORONARY_ANGIOGRAM',
              pattern=[{'LOWER': {'IN': ['coronary', 'heart']}},
                       {'LOWER': {'IN': ['angiogram', 'angio', 'cath', 'catheterization']}}]),
     TargetRule("MAZE", category='MAZE', pattern=[{'LOWER': {'IN': ['maze']}}]),
     TargetRule("lvad", category='lvad', pattern=[{'LOWER': {'IN': ['lvad']}}]),
     TargetRule("lvad", category='lvad', pattern=[{'LOWER': {'IN': ['left ventricular assist device']}}]),
     TargetRule("mvr", category='mvr', pattern=[{'LOWER': {'IN': ['mvr']}}]),
     TargetRule("avr", category='avr', pattern=[{'LOWER': {'IN': ['mvr']}}]),
     TargetRule("tvr", category='tvr', pattern=[{'LOWER': {'IN': ['tvr']}}]),
     TargetRule("mvr", category='mvr',
              pattern=[{'LOWER': {'IN': ['mitral']}},
                       {'LOWER': {'IN': ['valve', 'valvulopathy']}},
                       {'LOWER': {'IN': ['repair', 'replacement', 'replaced']}}]),
     TargetRule("avr", category='avr',
              pattern=[{'LOWER': {'IN': ['aortic']}},
                       {'LOWER': {'IN': ['valve', 'valvulopathy']}},
                       {'LOWER': {'IN': ['repair', 'replacement', 'replaced']}}]),
     TargetRule("tvr", category='tvr',
              pattern=[{'LOWER': {'IN': ['tricuspid']}},
                       {'LOWER': {'IN': ['valve', 'valvulopathy']}},
                       {'LOWER': {'IN': ['repair', 'replacement', 'replaced']}}]),
     TargetRule("cabg", "cabg"),
     TargetRule("cab", "cabg"),
     TargetRule("cabg x1", "cabg",
              pattern=[{"lower": {"in": ["cabg", "cab"]}},
                       {"lower": {"in": ["x1", "x2", "x3", "x4"]}}]),
     TargetRule("coronary artery bypass graft", "cabg"),
     TargetRule("coronary artery bypass", "cabg"),
     TargetRule("coronary artery bypass grafting", "cabg"),
     TargetRule("impella", "impella"),
     TargetRule("abdominal aortic aneurysm", "disease"),
     TargetRule("aaa", "aaa"),
     TargetRule("triple a", "aaa"),
     TargetRule("aortic aneurysm", "aaa"),
     TargetRule("oht", "oht"),
     TargetRule("aortic dissection", "aortic_dissection",
              pattern=[{'LOWER': {'IN': ['aortic', 'ascending', 'aorta']}},
                       {'LOWER': {'IN': ['dissection', 'tear']}}]),
     TargetRule("oht", "oht",
              pattern=[{'LOWER': {'IN': ['orthotopic', 'heart', 'cardiac']}},
                       {'LOWER': {'IN': ['transplant', 'transplantation']}}]),
     TargetRule("craniotomy", "craniotomy"),
     TargetRule("craniectomy", "craniectomy"),
     TargetRule("kyphoplasty", "kyphoplasty"),
     TargetRule("ivor-lewis esophagectomy", "ivorlewis"),
     TargetRule("ivor lewis esophagectomy", "ivorlewis"),
     TargetRule("ivor lewis", "ivorlewis"),




]

target_matcher.add(target_rules)

context = nlp.add_pipe("medspacy_context", config={"rules": None})

context_rules = [
    ConTextRule(literal='history', category='HISTORICAL', pattern=[{'LOWER': {'IN': ['Past Medical History:', 'pmhx', 'pmh', 'history', 'past', 'hx', 'hist', 'ho']}}], direction='FORWARD'),
   # ConTextRule(literal='active', category='ACTIVE', pattern=[{'LOWER': {'IN':'active medical', 'active'}}], direction='FORWARD'),
    ConTextRule(literal='h/o', category='HISTORICAL', pattern=None, direction='FORWARD'),
    ConTextRule(literal='past history', category='HISTORICAL', pattern=[{'LOWER': 'past'}, {'LOWER': 'history', 'OP': '?'}], direction='FORWARD'),
    ConTextRule(literal='past medical', category='HISTORICAL', pattern=[{'LOWER': 'past'}, {'LOWER': 'medical', 'OP': '?'}, {'LOWER': 'history'}], direction='FORWARD'),
    ConTextRule(literal='past medical history', category='HISTORICAL', pattern=[{'LOWER': 'past'}, {'LOWER': 'medical', 'OP': '?'}, {'LOWER': 'history'}], direction='FORWARD'),
    ConTextRule(literal='active history', category='ACTIVE', pattern=[{'LOWER': 'active'}, {'LOWER': 'history', 'OP': '?'}], direction='FORWARD'),
    ConTextRule(literal='active medical history', category='ACTIVE', pattern=[{'LOWER': 'active'}, {'LOWER': 'medical', 'OP': '?'}, {'LOWER': 'history'}], direction='FORWARD'),
    ConTextRule(literal='active medical', category='ACTIVE', pattern=[{'LOWER': 'active'}, {'LOWER': 'medical', 'OP': '?'}], direction='FORWARD'),
    ConTextRule(literal='separate active', category='HISTORICAL', pattern=[{'LOWER': 'active'}, {'LOWER': 'history', 'OP': '?'}], direction='BACKWARD'),
    ConTextRule(literal='separate active medical', category='HISTORICAL', pattern=[{'LOWER': 'active'}, {'LOWER': 'medical', 'OP': '?'}, {'LOWER': 'history'}], direction='BACKWARD'),
    ConTextRule(literal='separate medical', category='HISTORICAL', pattern=[{'LOWER': 'active'}, {'LOWER': 'medical', 'OP': '?'}], direction='BACKWARD'),
    ConTextRule(literal='separate', category='HISTORICAL', pattern=[{'LOWER': {'IN': ['separate', 'separator']}}], direction='BACKWARD'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='diagnosed in ', category='HISTORICAL', pattern=[{'LOWER': 'diagnosed'}, {'LOWER': 'in'}, {'LOWER': {'REGEX': '^[\\d]{4}$'}}], direction='BIDIRECTIONAL'),
    ConTextRule(literal='surgeon', category='surgeon', pattern=[{'LOWER': {'IN': ['surgeon', 'surgeon(s)']}}], max_targets = 1, direction='FORWARD'),
    ConTextRule(literal='surgeon', category='surgeon', pattern=None, max_targets = 1, direction='FORWARD'),
    ConTextRule(literal='procedure', category='procedure', pattern=[{'LOWER': {'IN': ['procedure', 'procedure:','procedure(s)', 'procedures', 'procedures:']}}], max_targets = 1, direction='FORWARD'),
    #ConTextRule(literal='active', category='STOP', pattern=[{'LOWER': {'IN': ['active']}}], direction='TERMINATE'),

]

context.add(context_rules)

sectionizer = nlp.add_pipe("medspacy_sectionizer")

section_patterns = [
    SectionRule("Brief Hospital Course:", "hospital_course",  "HISTORY_OF_PRESENT_ILLNESS" ),
    SectionRule(literal="PAST MEDICAL HISTORY:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="past medical history:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Current Medical Problems:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="HISTORY:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="past history", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="CLINICAL HISTORY:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="History of Chronic Illness:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="MHx:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="PAST HISTORY:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="past med history:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="past", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="past medical hx:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="PAST SURGICAL HISTORY:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="PMH:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="PMHx:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="UNDERLYING MEDICAL CONDITION:", category="past_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Family History:", category="family_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="FAMILY HISTORY:", category="family_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Fam Hx:", category="family_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Family Hx:", category="family_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Fam/Hx:", category="family_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Fam_Hx:", category="family_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="Assessment and Plan", category="observation_and_plan", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="ACTIVE MEDICAL HISTORY:", category="active_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="active medical history", category="active_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="active medical", category="active_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),
    SectionRule(literal="active", category="active_medical_history", pattern=None, on_match=None, parents=[], parent_required=False),

]

sectionizer.add(section_patterns)

postprocessor = nlp.add_pipe("medspacy_postprocessor")



postprocess_rules = [
    # Instantiate our rule
    PostprocessingRule(
        # Pass in a list of patterns
        patterns=[
            # The pattern will check if the entitie's section is "patient_instructions"
            PostprocessingPattern(condition=lambda ent: ent._.section_category, success_value="past_medical_history"),
        ],
        # If all patterns are True, this entity will be removed.
        action=postprocessing_functions.set_historical,
        description="Remove any entities from the instructions section."
    ),

]