
#medical workup
Dx5Wk1 = "Pt presents with evidence of acute coronary syndrome. Ddx includes type 1 versus type 2.  Suspect NSTEMI."
Dx5Wk2 = "Pt presents with evidence of unstable angina."
Dx5Wk3 = "Pt presents with evidence of acute coronary syndrome and cardiac arrest."
Dx5Wk4 = "Pt presents with evidence of ischemia in setting of bleeding.  Will need to maximize O2 delivery and minimize myocardial O2 demand without compromising hemodynamics."
Dx5Wk5 = "Pt presents with evidence of ischemia in setting of Coagulopathy.  Will need to maximize O2 delivery and minimize myocardial O2 demand without compromising hemodynamics."
Dx6Wk1 = "Pt with evidence of AAA on imaging."
Dx6Wk2 = "Pt with AAA and tachycardia.  Will need to reduce shear stress on flap."
Dx6Wk3 = "Pt presents with evidence of AAA and CHF concerning for possible aortic valvulopathy."
Dx6Wk4 = "Pt with AAA and hypertension, will need to control HR and BP."
Dx6Wk5 = "Pt with AAA and evidence of hypotension and malperfusion.  Unclear if cardiogenic versus hypovolemic."
Dx7Wk1 = "Pt with evidence of Tachycardia unclear if sinus vs SVT.  Will obtain EKG."
Dx7Wk2 = "Pt with tachycardia in setting of CHF.  If SVT will need to control chemically vs cardioversion."
Dx7Wk3 = "Pt noted to be both hypertensive and tachycardic.  Will need to control BP and HR."
Dx7Wk4 = "Pt noted to be both hypertensive and tachycardic in setting of Respiratory failure.  Will need to place on ventilatory support relieve anxiety or pain and then consider drugs to reduce HR and BP."
Dx7Wk5 = "Pt noted to have hypotension and tachycardia.  Will need to evaluate whether sinus or SVT."
Dx7Wk6 = "Pt noted to have tachycardia in setting of obstructive lung disease and neb use."
Dx7Wk7 = "Pt with tachycardia in setting of PE"
Dx7Wk8 = "The pt has afib with RVR"
Dx7Wk9 = "The pt is noted to have unstable afib with RVR and is hypotensive"
Dx8Wk1 = "Pt with bradycardia will need EKG to determine if heart block versus sinus brady vs junctional"
Dx8Wk2 = "Pt with evidence of bradycardia and heart failure.  Will need to increase rate to improve cardiac output and perfusion."
Dx8Wk3 = "Pt with hypertension and bradycardia, this may be reflexive versus concurrent."
Dx8Wk4 = "The pt has hypotension and bradycardia.  Etiology unclear but the differential includes ischemia, electrophysiologic disease, drug related."
Dx9Wk1 = "The pt has evidence of CHF.   Will need echo to determine whether HFpEF, HFrEF."
Dx9Wk2 = "The pt has HTN emergency with resultant CHF exacerbation.  Will need to preload and afterload reduce as well diurese patient."
Dx9Wk3 = "The pt has decompensated heart failure and evidence of cardiogenic shock.  Will need to improve cardiac output."
Dx9Wk4 = "The pt presents with cardiac arrest and evidence of cardiogenic shock."
Dx9Wk5 = "The pt has evidence of CHF with pulmonary edema and severe respiratory failure.  Will need need improve preload afterload and assist with respiration."
Dx9Wk6 = "Pt noted to have evidence of CHF in setting of liver failure.  Unclear etiology but ddx includes hepatic hydrothorax, venous congestion, aspiration."
Dx9Wk7 = "PT presents with pulmonary edema and evidence of endocarditis with possible valvular regurgitation."
Dx9Wk8 = "Pt presents with SAH and now has pulmonary edema likely from sympathetic surge."
Dx9Wk9 = "Pt with evidence of CHF as well as AKI which could represent a cardiorenal syndrome."
Dx10Wk1 = "Pt presents with HTN urgency/emergency."
Dx10Wk2 = "Pt has HTN urgency in setting of respiratory failure."
Dx10Wk3 = "PT with hypertension in setting of ICH.  Will need to reduce systolic blood pressure <160."
Dx10Wk4 = "PT with hypertension in setting of subdural hemorrhage.  Will need to reduce systolic blood pressure <160"
Dx10Wk5 = "PT with hypertension in setting of subarachnoid hemorrhage.  Will need to reduce systolic blood pressure <140 until source of bleed resolved."
Dx10Wk6 = "Pt with known space occupying lesion as well as HTN and bradycardia.  Will need to evaluate for possible cushing reflex."
Dx10Wk7 = "Pt with HTN in setting of renal dysfunction.  Will need to evaluate volume status and if overloaded diurese or consider RRT."
Dx11Wk1 = "Pt in shock the subtype of which is unclear.  The differential diagnosis includes cardiogenic, distributive, hypovolemic, obstructive shock."
Dx11Wk2 = "Pt in shock the subtype of which is unclear.  The differential diagnosis includes cardiogenic, distributive, hypovolemic, obstructive shock.  Because pt has evidence of PNA, this  may be pneumonia with septic shock."
Dx11Wk3 = "Pt in shock the subtype of which is unclear.  The differential diagnosis includes cardiogenic, distributive, hypovolemic, obstructive shock.  Because pt has evidence of pneumothorax, this may be obstructive."
Dx11Wk4 = "Pt in shock the subtype of which is unclear.  The differential diagnosis includes cardiogenic, distributive, hypovolemic, obstructive shock.  Because pt has evidence PE this may be massive PE and obstructive shock."
Dx11Wk5 = "Pt is hypotensive in setting of liver failure.  The differential diagnosis includes cardiogenic, distributive, hypovolemic, obstructive shock.  Will evaluate for bleed and infection."
Dx11Wk6 = "PT has evidence of hypotension in setting of active GI bleed.  Will need to volume resuscitate and stop source of bleed."
Dx11Wk7 = "Pt in shock the subtype of which is unclear.  The differential includes cardiogenic, distributive, hypovolemic, obstructive shock.  Because pt has evidence of colitis will need to monitor for toxic megacolon."
Dx11Wk8 = "Pt presents with evidence of hypotensions in setting of bacteremia and so shock state likely septic shock."
Dx11Wk9 = "Pt in shock the subtype of which is unclear.  The differential includes cardiogenic, distributive, hypovolemic, obstructive shock.  The pt has evidence of infection and so this is possibly septic shock."
Dx12Wk1 = "Pt presents after cardiac arrest and achievement of ROSC. Unclear if PEA vs Vtach/Vfib."
Dx12Wk2 = "Pt presents after cardiac arrest and achievement of ROSC. Unclear if PEA vs Vtach/Vfib.  Pt now in cardiogenic shock as well.  Will need to begin pressor and inotrope."
Dx12Wk3 = "The pt has suffered cardiac arrest in setting of PE.  The pt may need emergent thrombolysis vs ECMO"
Dx12Wk4 = "Pt noted to have PEA arrest with bradycardia."
Dx13Wk1 = "Etiology of airway obstruction unclear, ddx includes stenosis, scarring, tumor, edema."
Dx14Wk1 = "Pt noted to have history/exam which is suggestive of COPD."
Dx14Wk2 = "Pt with evidence of ischemia and pulmonary outflow obstruction unclear if cardiac wheezing versus COPD."
Dx14Wk3 = "The pt has evidence of COPD and tachycardia likely from neb use vs acidemia."
Dx14Wk4 = "The pt has COPD and pneumonia."
Dx14Wk5 = "The pt has a history of COPD and has radiographic evidence of PTX.  It is unclear if this is related to bleb or true PTX."
Dx14Wk6 = "The pt is having increased work of breathing in setting of COPD likely exacerbation"
Dx14Wk7 = "The pt is having severely increased work of breathing in setting of COPD exacerbation requiring intubation"
Dx15Wk1 = "Pt noted to have consolidation on CXR with evidence of SIRS consistent with pneumonia"
Dx15Wk2 = "Pt with evidence of PE and PNA on radiology.  Unclear if aspiration vs pneumonia vs pulmonary infarct"
Dx15Wk3 = "PT with pneumonia in setting of liver disease, will treat and monitor for mental status changes and aspiration"
Dx15Wk4 = "The patient has pneumonia in setting of bacteremia which could be septic emboli"
Dx15Wk5 = "The patient has pneumonia in setting of endocarditis and bacteremia which could be septic emboli"
Dx16Wk1 = "Pt with evidence of pneumothorax on CXR."
Dx17Wk1 = "Pt with evidence of respiratory failure."
Dx17Wk2 = "Pt with respiratory failure and hypotension etiology unclear however ddx includes acidemia, sedation related, autopeep"
Dx17Wk3 = "The pt present with respiratory failure in setting of obstructive lung disease"
Dx17Wk4 = "The pt has evidence of acute respiratory failure with hypoxia"
Dx17Wk5 = "The patient has respiratory failure in setting of a pneumothorax.  Will need to perform needle decompression or tube thoracostomy emergently"
Dx17Wk6 = "Pt with evidence of PE and hypoxia"
Dx17Wk7 = "The pt has respiratory failure in setting of liver disease.  Unclear etiology but ddx includes aspiration, hepatic encephalopathy, pneumonia, pulmonary edema, hepatopulmonary syndrome or portopulmonary syndrome"
Dx17Wk8 = "The patient has respiratory failure in setting of neurologic dysfunction.  Will need to protect airway"
Dx18Wk1 = "Pt with evidence of PE."
Dx18Wk2 = "Pt noted to have PE however also exhibits bleeding precluding ability to place on anticoagulation or tPA"
Dx18Wk3 = "Pt noted to have PE however also at increased risk of bleeding which precludes ability to place on anticoagulation or tPA"
Dx19Wk1 = "Pt with evidence of liver failure from likely hepatitis vs tylenol overdose vs etoh vs autoimmune."
Dx19Wk2 = "Pt with liver failure and lower extremity cellulitis likely from elevated portal vein pressures"
Dx20Wk1 = "Pt has evidence of GIB etiology of which is unclear."
Dx20Wk2 = "The pt presents with GI bleed in setting of liver dysfunction.  DDx includes variceal bleed vs PUD vs colon related."
Dx20Wk3 = "Pt has evidence of GIB as well as ACS.  Will need to transfuse however cannot give antiplatelet or heparin yet"
Dx21Wk1 = "Pt has evidence of pancreatitis etiology unclear ddx includes idiopathic vs alcohol vs gallstone vs drug related vs hypertriglyceridemia."
Dx22Wk1 = "Pt with evidence of colitits, ddx includes ischemic, infectious, inflammatory."
Dx22Wk2 = "Pt presents with evidence of Cdiff colitis."
Dx23Wk1 = "Pt with evidence of gastroenteritis, unclear if viral vs bacterial."
Dx24Wk1 = "Pt has evidence of SBO"
Dx25Wk1 = "Pt with positive blood cultures. Source of infection is unclear at present."
Dx25Wk2 = "Pt with positive blood cultures. Source of infection is unclear at present however pt also with pneumonia and so may be pulmonary"
Dx25Wk3 = "Pt with positive blood cultures. Source of infection is unclear at present however pt with evidence of liver failure and so may be related to gut translocation versus sbp versus pneumonia"
Dx25Wk4 = "Pt with positive blood cultures. Source of infection is unclear at present however pt with GI sepsis and so that may be the source"
Dx25Wk5 = "Pt with positive blood cultures. Source of infection is unclear however patient has evidence of CNS infection.  Will need to monitor for pneumococcus versus neisseria versus listeria"
Dx25Wk6 = "Pt with positive blood cultures and evidence of vegetation on echo suggesting possible endocarditis"
Dx25Wk7 = "Pt with positive blood cultures. Source of infection is unclear at present however patient has UTI with sepsis and so that may be the source"
Dx25Wk8 = "Pt with positive blood cultures. Source of infection is unclear at present however patient has cellulitis with sepsis and so that may be the source.  Will need to check for necrotizing fasciitis"
Dx26Wk1 = "Pt with signs and symptoms of meningitis."
Dx26Wk2 = "The patient has evidence of both meningitis and endocarditis which may represent seeding from bacteremia versus a component of Austrian's triad"
Dx27Wk1 = "Pt with evidence of endocarditis"
Dx28Wk1 = "Pt noted to have ICH on CT scan, etiology of which unclear ddx includes amyloid vs AVM vs trauma vs spontaneous"
Dx28Wk2 = "Pt noted to have ICH on CT scan, etiology of which unclear ddx includes amyloid vs AVM vs trauma vs spontaneous.  The pt also noted to be hypertensive and so will need to control."
Dx28Wk3 = "Pt noted to have evidence of ICH and SDH on CT scan, etiology of which unclear ddx includes amyloid vs AVM vs trauma vs spontaneous.  The pt also noted to be hypertensive and so will need to control"
Dx28Wk4 = "Pt noted to have evidence of ICH and SAH on CT scan, etiology of which unclear ddx includes amyloid vs AVM vs trauma vs spontaneous.  The pt also noted to be hypertensive and so will need to control"
Dx28Wk5 = "Pt noted to have ICH on CT scan complicated by seizures.  The etiology of the bleed is unclear, ddx includes amyloid vs AVM vs trauma vs spontaneous.  The will need to control seizures"
Dx28Wk6 = "Pt noted to have ICH on CT scan in setting of possible brain tumor.  Tumor likely led to bleeding.  Will need to control BP, reverse coagulopathy monitor airway."
Dx29Wk1 = "Pt noted to have SDH on CT scan, etiology of which unclear ddx includes trauma vs spontaneous"
Dx29Wk2 = "Pt noted to have SDH on CT scan, etiology of which unclear ddx includes trauma vs spontaneous.  PT with hypertension and so will need to monitor for cushings reflex as well as control pressure."
Dx29Wk3 = "Pt noted to have SDH on CT scan, etiology of which unclear ddx includes trauma vs spontaneous now complicated by seizures."
Dx29Wk4 = "Pt noted to have SDH on CT scan, etiology of which unclear ddx includes trauma vs spontaneous.  PT also noted to have evidence of brain tumors which could be reponsible for bleeding."
Dx29Wk5 = "Pt noted to have SDH on CT scan, etiology of which unclear ddx includes trauma vs spontaneous.  PT with hypertension and so will need to monitor for cushings reflex as well as control pressure.  Pt with coagulopathy which will need to be corrected."
Dx30Wk1 = "Pt found to have SAH on CT scan.  Etiology unclear however ddx includes aneurysmal versus trauma."
Dx30Wk2 = "Pt found to have SAH on CT scan.  Etiology unclear however ddx includes aneurysmal versus trauma.  Pt course being complicated by seizures"
Dx31Wk1 = "Pt with evidence of seizures.  Cause of seizures is unclear ddx includes med noncompliance, toxic metabolic disturbance, brain tumor, ingestion, fatigue, CVA."
Dx32Wk1 = "Pt with evidence of brain tumor on imaging"
Dx33Wk1 = "Pt with evidence of UTI with sepsis"
Dx34Wk1 = "Pt noted to have signs of soft tissue infection"
Dx34Wk2 = "Pt noted to have signs of soft tissue infection. Pt noted to have signs of soft tissue infection in setting of delirium, will need to evaluate for possible necrotizing fasciitis. "
Dx35Wk1 = "Pt found to have infectious colitis on cdiff assay."
Dx36Wk1 = "Pt with history of DM."
Dx37Wk1 = "Pt presents with AKI, etiology of which is unclear.  DDx includes prerenal vs post renal vs intrinsic."
Dx38Wk1 = "Pt noted to have elevated FS and AG consistent with DKA."
Dx39Wk1 = "Pt noted to be anemic, etiology of which is unclear ddx includes macro vs micro vs normocytic."
Dx40Wk1 = "Pt with low glucose level"
Dx41Wk1 = "Pt noted to have elevated sodium for unclear reasons.  DDx includes dietary vs diabetes insipidus vs diuretic related"
Dx42Wk1 = "Etiology of hyponatremia unclear.  Ddx includes hypovolemic vs euvolemic vs hypervolemic"
Dx43Wk1 = "Pt with hyperkalemia etiology unclear ddx includes renal failure vs acidemia vs drug related vs rhabdo vs tumor lysis"
Dx44Wk1 = "Pt with hypokalemia"
Dx45Wk1 = "Pt noted to have coagulopathy"
Dx45Wk2 = "Pt noted to have coagulopathy and bleeding"
Dx46Wk1 = "Pt HD stable monitor vitals"
Dx47Wk1 = "Promote IS use, keep o2 sat >92%"
Dx48Wk1 = "Advance diet when ok with primary"
Dx49Wk1 = "Monitor for AKI and replete lytes"
Dx50Wk1 = "Monitor for delirium"
Dx51Wk1 = "Monitor for bleeding and blood clots.  Transfuse for hgb < 7 and platelets <10"
Dx52Wk1 = "Maintain FS 150-180"
Dx53Wk1 = "Monitor for infection"
Dx57Wk1 = "The pt is noted to be on ventilator for respiratory support and airway protection"
Dx57Wk2 = "The pt is now intubated in the setting of CHF exacerbation.  Will need positive pressure to reduce afterload"
Dx57Wk3 = "The pt is intubated after episode for cardiac arrest and ROSC"
Dx57Wk4 = "The pt is intubated in setting of COPD, PNA and respiratory failure"
Dx57Wk5 = "Will need lung protective ventilation, minimize O2, permissive hypercapnia, TV 6cc/kg, high PEEP."
Dx57Wk6 = "The pt has evidence of COPD exacerbation and respiratory failure in the setting of PNA"
Dx58Wk1 = "The pt is found to have afib unclear if paroxysmal or persistent."
Dx58Wk2 = "The pt is found to have afib unclear if paroxysmal or persistent in setting of bleeding risk."
Dx59Wk1 = "The pt is found to have an anion gap acidosis of unclear cause.  The differential is elevated levels of methanol, urea, keto acidosis, starvation ketosis, lactic acidosis, ethanol, isoniazid, salicylates or possible paraldehyde"
Dx59Wk2 = "The pt is found to have DKA.  The possible causes include med noncompliance, infection, new diagnosis, worsening insulin production"
Dx59Wk3 = "The pt is noted to have a negative anion gap.  DDx includes possible hypoalbuminemia vs paraproteinemia including MGUS, multiple myeloma vs high cation state such as Li+ Ca++, Mg++ vs lab error"
Dx60Wk1 = "The pt has history of ESRD"
Dx61Wk1 = "The pt has history of CKD"
Dx62Wk1 = "The pt has a history of HTN"
Dx62Wk2 = "The pt has a history of HTN however the BP is low at present"
Dx63Wk1 = "The pt has history of asthma"
Dx63Wk2 = "The Pt noted to have asthma exacerbation and increased work of breathing likely"
Dx64Wk1 = "The pt has a EtOH use and now with tremor and signs of alcohol withdrawal"
Dx64Wk2 = "The pt has a EtOH use and now with signs of severe withdrawal requiring intubation."
Dx65Wk1 = "The pt has a history of CAD."
Dx65Wk2 = "The pt has a history of CAD in setting of bleeding risk"
Dx66Wk1 = "The pt has a history of OSA."
Dx67Wk1 = "The pt has a history of hypothyroid."
Dx68Wk1 = "The pt has a history of hyperthyroidism."
Dx69Wk1 = "The pt has evidence of ischemic stroke.  Neuro deficit as is noted"
Dx69Wk2 = "The pt has evidence of ischemic stroke.  Neuro deficit as is noted.  The pt is noted to have coagulopathy."
Dx69Wk3 = "The pt has evidence of ischemic stroke.  Neuro deficit as is noted.  The pt is noted to also have bleeding."
Dx69Wk4 = "The pt has evidence of ischemic stroke. Neuro deficit as is noted. The pt is noted to also have brain tumor."
Dx70Wk1 = "The pt has evidence of delirium."
Dx71Wk1 = "The pt has a history of dyslipidemia"
Dx72Wk1 = "The pt has a history of lupus."
Dx72Wk2 = "The pt has history of lupus now with HTN emergency, will need to monitor for possible lupus flare."
Dx72Wk3 = "The pt has hx of respiratory failure and lupus, will need to monitor for pneumonitis vs serositis."
Dx72Wk4 = "The pt has lupus and now encephalitis. Will need to monitor of lupus cerebritis."
Dx72Wk5 = "The pt has hx of lupus now with AKI, will need to evaluate for lupus nephritis."
Dx72Wk6 = "The pt has lupus and now seizures. Will need to monitor of lupus cerebritis."
Dx73Wk1 = "The pt has a hx of sclerderma and signs of scleroderma"
Dx74Wk1 = "The pt has a history of pericardial effusion unclear etiology ddx includes infectious, rheumatologic, malignant or idiopathic."
Dx74Wk2 = "The pt has pericardial effusion in setting of AAA. Will need to monitor for extension of dissection."
Dx74Wk3 = "The pt has pericardial effusion in setting of shock state. The pt is high risk of having pericardial tamponade."
Dx74Wk4 = "The pt has a history of pericardial effusion unclear etiology ddx includes infectious, rheumatologic, malignant or idiopathic. Pt with renal failure which might explain pericardial effusion."
Dx74Wk5 = "The pt has a history of pericardial effusion unclear etiology ddx includes infectious, rheumatologic, malignant or idiopathic. Pt with lupus which might explain pericardial effusion."
Dx75Wk1 = "The pt has evidence of cholecystitis. The cause is unclear but ddx includes stones vs tumor vs stricture"
Dx76Wk1 = "The pt is showings signs of adrenal insufficiency.  It is unclear if primary or secondary"
Dx77Wk1 = "The pt has signs and symptoms of hypercortisolemia.  It is unclear whether primary or secondary"
Dx78Wk1 = "The pt is noted to have diffuse non-cardiac consolidation with P/F <300 consistent with ARDS"
Dx79Wk1 = "The pt has recent head trauma"
Dx80Wk1 = "The pt has burns will need to evaluate thickness fraction of BSA affected."
Dx81Wk1 = "The pt has a history of peripheral vascular disease."
Dx82Wk1 = "The pt has a evidence of brain mass."
Dx83Wk1 = "The pt has a history of GERD"
hist2=  "The pt has a history of MI."
hist3=  "The pt has a history of AAA."
hist6   ="The pt has a history of CHF."
hist11= "The pt has a history of pneumonia in the past."
hist12= "The pt has a history of COPD."
hist13= "The pt has had pneumothorax in the past."
hist15= "The pt has a hx of cirrhosis."
hist16= "The pt has had GIB in the past."
hist17= "The pt has had pancreatitis in the past."
hist18= "The pt has a history of colitis."
hist21= "The pt has a history of endocarditis."
hist22= "The pt has had previous UTI."
hist23= "The pt has a history of being vented"
hist24= "The pt has a history of afib."
hist30= "The pt has a history of DM."
hist33= "The pt has a history of PE."
hist34= "The pt has a history of ICH."
hist35= "The pt has a history of SDH."
hist36= "The pt has a history of SAH."
hist37= "The pt has a history of Seizures."
hist41= "The pt has history of asthma"
hist43= "The pt has had etoh withdrawal in the past"
hist48= "The pt has a history of CVA"
hist52= "The pt has a history of lupus"
hist54  ="The pt has a history of scleroderma"
hist55= "The pt has a history of pericardial effusion"
hist58= "The pt has a history of cellulitis"
hist59= "The pt has a history of TBI"
hist61= "The pt has a history of PAD"
hist62= "The pt has a history of brain tumor"
hist74= "The pt has chronic pleural effusions"
hist75= "The pt has a history of trach"

#history library
Hemicolectomy = "hemicolectomy"
Colon_cancer = ['colon ca', 'colon cancer']
ACS = ['acs' ,'stemi', "mi", "nstemi", "stemi", "heart attack", "myocardial infarction"]
AAA = ["abdominal aortic aneurysm", "triple a", "aaa", "aortic aneurysm", "abd aorta enlarged", "enlarged aorta", "abdominal aortic aneurysm", "aaa", "triple a", "aortic aneurysm"]
Abdominal_Pain = ["abdominal pain", "abdominal discomfort", "stomach pain", "gastric distress", "ruq pain", "luq pain", "rlq pain", "llq pain"]
Tachycardia = ["tachycardia", "tachycardia", "tachycardic", "svt", "afib with rvr", "vtach", "ventricular tachycardia"]
Bradycardia = ["bradycardia", "heart block", "wenckebach"]
CHF = ["chf", "hfref", "hfpef", "cardiomyopathy", "congestive heart failure", "heart failure", "cardiac failure", "low ejection fraction", "low ef", "congestive heart"]
HTN_Emergency = ["malignant hypertension", "htn emergency", "htn crisis", "htn crisis" "hypertensive urgency", "hypertensive emergency", "hypertensive crisis"]
HypotensionShock = ["hypotension", "hypotension", "hypotensive", "shock", "malperfusion", "hypoperfuse", "hypoperfusion"]
Cardiac_arrest =["cardiac arrest", "cardiopulmonary arrest", "cardiac death"]
Airway_Obstruction = [ "airway obstruction", "tracheal stenosis", "airway stenosis", "obstruction", "laryngeal edema", "laryngeal mass", "vocal chord edema", "vocal chord swelling"]
COPD = ["copd", "copd", "chronic obstructive pulmonary disease", "chronic obstructive lung disease"]
Pneumonia = ["pna", "pneumonia", "cap", "hcap", "vap", "lung infection", "pulmonary infection", "lung infiltrate", "pulmonary infiltrate", "pulmonary consolidation"]
Pneumothorax = ["collapsed lung", "air around lung", "ptx", "ptx", "pneumothorax", "pneumothoraces"]
Respiratory_Failure = ["respiratory failure", "respiratory arrest", "respiratory failure","respiratory arrest","respiratory distress","resp failure","resp arrest", "resp distress", "pulmonary distress"]
PE = ["pe", "pulmonary embolus", "pulmonary embolism", "pulmonary clots", "saddle pe", "saddle clot", "saddle embolus"]
ALF = ["alcoholic liver cirrhosis", "liver failure", "liver cirrhosis", "hepatitis", "cirrhosis", "ascites", "cirrhotic", "varices", "hepatitis", "transaminitis"]
GI_Bleed = ["gi bleed", "gastrointestinal bleed", "gi bleed", "gi bleeding", "variceal bleed", "gastric bleed", "varcieal oozing", "intestinal bleeding", "gib", "hematchezia", "melena", "vomiting blood", "bright red blood per rectum", "brbpr"]
Pancreatitis = ["inflamed pancreas", "elevated lipase", "pancreatic inflammation", "pancreatitis"]
Colitis = ["colitis", "cdiff", "bowel infection", "gut inflammation", "bowel inflammation", "inflamed bowel"]
Gastroenteritis = ["gastroenteritis", "gastroenteritis", "enteritis"]
Bacteremia = ["blood infection", "positive blood culture", "gram negatives in blood", "+ blood culture", "bacteremia", "septicemia"]
Meningitis_encephalitis = ["meningitis", "nuchal rigidity", "cns infection", "encephalitis"]
Endocarditis = ["endocarditis", "vegetation", "septic emboli"]
ICH = ["ich", "ivh", "iph", "intracranial hemorrhage", "intracranial hemorrhaging", "intracranial bleed", "intracranial hematoma", "brain hemorrhage", "intracerebral bleed", "brain bleed", "cerebral hemorrhage", "intraventricular hemorrhage"]
SDH = ["sdh", "subdural hemorrhage", "subdural hemorrhaging", "subdural bleed", "subdural hematoma"]
SAH = ["sah", "subarachnoid hemorrhage", "subarachnoid hemorrhaging", "subarachnoid bleed", "subarachnoid hematoma"]
Seizures = ["seizure", "epilepsy", "convulsion", "pseudoseizure", "seizures", "convulsions", "pseudoseizures"]
UTI = ["urinary tract infection", "positive urine", "uti", "uti", "dysuria"]
Cellulitis = ["cellulitis" "skin infection", "skin inflammation", "nec fasc", "necrotizing fasciitis", "cellulitic"]
DM = ["diabetes mellitus", "DMT2", "dm", "dm", "diabetes", "iddm", "dm1", "dm2", "iddm1"]
AKI = ["aki", "kidney injury", "acute kidney injury", "acute renal injury", "acute kidney failure"]
DKA = ["diabetic ketoacidosis", "diabetic ketosis", "ketoacidosis", "ketoacidotic", "ketosis", "dka"]
Afib = ["atrial fib", "tachycardia", "afib", "a fib", "a-fib", "atrial fibrillation"]
ESRD = ["esrd", "end-stage renal disease", "end stage kidney disease"]
CKD = ["ckd", "ckd1", "ckd2", "ckd3", "ckd4", "ckd5", "ckdii", "ckdii", "ckdiii", "ckdiv", "ckdv", "chronic kidney disease", "chronic renal disease", "chronic renal dysfunction" "kidney disease"]
HTN = ["hypertension", "htn", "hipertension", "hypertensive", "high blood pressure", "elevated blood pressure"]
Asthma = ["asthma", "asthmatic"]
EtOH_WD = ["alcohol withdrawal", "alcohol hallucinosis", "etoh wd", "etoh withdrawal",  "alcoholic", "delirium tremens"]
CAD = ["coronary artery disease", "coronary disease", "coronary dz", "heart disease", "coronary vessel disease"]
OSA = ["osa", "obstructive sleep apnea", "sleep apnea"]
Hypothyroid = ["hypothyroidism", "hypothyroid", "myxedema", "hypoactive thyroid", "myxedema coma"]
Hyperthyroid = ["hyperactive thyroid", "hyperthyroidism", "hyperthyroidism", "hyperthyroid", "graves"]
CVA = ["cva", "stroke", "ischemic stroke", "mca", "pca", "aca", "cerebrovascular accident"]
Delirium = ["delirium", "confusion", "sundowning", "sundown", "sundowning", "confused", "delirious", "encephalopathy", "encephalopathic"]
DLD = ["hyperlipidemia", "hld", "dld", "dyslipidemia", "dyslipidemic", "hyperlipidemic", "hypertriglyceridemia", "high cortisol"]
Lupus = ["lupus", "sle", "systemic lupus erythematosus", "lupus erythematosus", "systemic lupus"]
Scleroderma = ["systemic sclerosis", "scleroderma", "crest", "sclerodactyly"]
Pericardial_Effusion = ["hemopericardium", "pneumopericardium", "pericardial effusion", "pericardial effusion", "pericardial tamponade", "pericardial fluid"]
Cholecystitis = ["cholecystitis", "gallbladder inflammation", "necrotic gallbladder", "gallbladder edema"]
AI = ["adrenal insufficiency", "ai", "low cortisol", "cushings disease", "hypocortisolemia", "hypoaldosteronism", "hypoaldosterone"]
Cushing = ["cushings", "hypercortisolemia", "hyperaldosteronism", "hyperaldosterone", "cushingoid", "cushing"]
ARDS = ["ards", "acute respiratory distress syndrome", "respiratory distress syndrome"]
TBI = ["traumatic brain injury", "brain injury", "brain trauma", "tbi"]
Burns = ["burn", "burns", "thermal injury"]
PAD = ["pvd", "pad", "peripheral artery disease", "peripheral vascular disease", "peripheral arterial disease"]
Brain_Tumor = ["gbm", "glioblastoma", "astrocytoma", "brain tumor", "brain mass", "glioblastoma", "cerebral met", "brain met", "brain metastasis"]
GERD = ["gerd", "gastroesophageal reflux disease", "gastroesophageal reflux", "gastric reflux", "reflux disease"]
Pleural_effusion = ["hemothorax", "pleural effusion", "pleural fluid", "lung edema", "complicated effusion", "loculated effusion"]
Vented = ["intubated", "vented" "ventilator use"]
trach = ["trach", "tracheostomy", "trached"]
extremity_angiogram = ["extremity balloon angioplasty", "extremity_angiogram", 'rue angiogram', 'rle angiogram', 'lle angiogram', 'lue angiogram', "extremity balloon angiogram", "extremity_angio", 'rue angio', 'rle angio', 'lle angio', 'lue angio']
lung_transplant = ["transplantation lung", "lung_transplant", "transplantation lung", "transplant lung"]
pericardial_window = ['pericardial window']
coronary_angiogram = ['coronary angiogram', 'rhc', 'lhc', 'coronary angiogram', 'heart angiogram', 'coronary angio', 'heart angio', 'coronary cath', 'heart cath', 'coronary catheterization', 'heart catheterization']
maze = ["maze", "mini maze"]
lvad = ['lvad', 'left ventricular assist device']
mvr = ['mvr', 'mitral valve repair', 'mitral valve replacement', 'mitral valve replaced', 'mitral valvulopathy repair', 'mitral valvulopathy replacement', 'mitral valvulopathy replaced']
avr = ['avr', 'aortic valve repair', 'aortic valve replacement', 'aortic valve replaced', 'aortic valvulopathy repair', 'aortic valvulopathy replacement', 'aortic valvulopathy replaced']
tvr = ['tvr', 'tricuspid valve repair', 'tricuspid valve replacement', 'tricuspid valve replaced', 'tricuspid valvulopathy repair', 'tricuspid valvulopathy replacement', 'tricuspid valvulopathy replaced']
CABG = ["cabg", "cab", "cabg x1", "cabg x2", "cabg x3", "cabg x4", "coronary artery bypass graft", "coronary artery bypass grafting", "coronary artery bypass"]
impella = "impella"
oht = ["oht", "orthotopic heart transplant", "heart transplant", "cardiac transplantation"]
aortic_dissection = ["aortic dissection", 'type 1 dissection', 'type 2 dissection']
craniotomy = ["craniotomy", "craniectomy"]
kyphoplasty = "kyphoplasty"
ivorlewis = ["ivor-lewis esophagectomy", "ivor lewis esophagectomy", "ivor lewis", "ivorlewis", "ivor-lewis"]